[package]
name = "udf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
poem = { path = "../../../../poem", default_features = false }
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17", features = ["macros", "rt"] }
