[package]
name = "poem-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { path = "../poem", version = "1.3.18", default_features = false }

tokio = { version = "1.17.0", features = ["rt"] }
